name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixar código
        uses: actions/checkout@v4

      - name: 🐍 Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Instalar dependências
        run: |
          pip install flet requests

      - name: ⚙️ Instalar Flet CLI
        run: pip install flet

      - name: 🚀 Build APK (automático sem travar)
        run: |
          yes | flet build apk main.py

      - name: 📤 Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/*.apk
